### PR TITLE
fix readme typo

### PR DESCRIPTION
**Pull request by vendethiel**

### CODE REVIEW

**Comment by rurban** [comment]
Thanks

**Comment by rurban** [comment]
Which name of yours should go into AUTHORS (similar to CREDITS in rakudo)
ven or Nami-Doc?

**Comment by vendethiel** [comment]
vendethiel. If rakudo still has Nami-Doc, I need to update it. Thanks.

**Comment by rurban** [comment]
Is ven also ok, your email name?

**Comment by vendethiel** [comment]
```
N: vendethiel
E: vendethiel@hotmail.fr
```

would that work? Name can be `ven` if that's prefered.

**Comment by rurban** [comment]
Will do that, yes. (the perl5 format is a bit different to rakudo/parrot). Done with e949b8679afd58c751740fa4847c3a4fdb97165c

**Pull request closed without merging**
