### PR TITLE
Smoke/win32fixes

### PR DESCRIPTION
**Pull request by bulk88**
For commit "partial revert "mingw: rename importlib to libcperl.a"" the test fails looked like

```
../cpan/B-C/t/c_argv.t                                          (Wstat: 512 Test
s: 4 Failed: 2)
  Failed tests:  1, 4
  Non-zero exit status: 2
../cpan/B-C/t/e_perlcc.t                                        (Wstat: 9216 Tes
ts: 87 Failed: 36)
  Failed tests:  1, 3-4, 6-7, 9-14, 17-18, 21, 23, 25, 27
                30-31, 33-34, 45-46, 48-49, 52, 62-65, 67
                69, 81, 83, 85, 87
  Non-zero exit status: 36
../cpan/B-C/t/modules.t                                         (Wstat: 4608 Tes
ts: 40 Failed: 18)
  Failed tests:  1, 3, 9, 11, 13, 15, 17, 19, 21, 23, 25
                27, 29, 31, 33, 35, 37, 39
  TODO passed:   6, 8
  Non-zero exit status: 18
```
```
C:\sources\cperl\win32>cd ..\t   & perl harness -v ../cpan/B-C/t/c_argv.t   & cd
 ..\win32
../cpan/B-C/t/c_argv.t ..
1..4
t\c_argv.pl syntax OK
ccode_argv.exe.c(773) : warning C4146: unary minus operator applied to unsigned
type, result still unsignedLINK : fatal error LNK1181: cannot open input file 'c
perl527.lib''ccode_argv.exe' is not recognized as an internal or external comman
d,
operable program or batch file.

#   Failed test 'perlcc -r file args'
#   at t/c_argv.t line 27.
not ok 1 - perlcc -r file args
#          got: ''
#     expected: 'ok 1
# '
t\c_argv.pl syntax OK
ccode_argv.exe.c(785) : warning C4146: unary minus operator applied to unsigned
type, result still unsigned
ccode_argv.exe.c(926) : warning C4102: 'lab_38db6c' : unreferenced label
ccode_argv.exe.c(913) : warning C4102: 'lab_38dcd8' : unreferenced label
ccode_argv.exe.c(906) : warning C4102: 'lab_38dc20' : unreferenced label
ccode_argv.exe.c(901) : warning C4102: 'lab_38db94' : unreferenced label
ccode_argv.exe.c(898) : warning C4102: 'lab_38dc6c' : unreferenced label
ccode_argv.exe.c(1136) : warning C4018: '<' : signed/unsigned mismatchLINK : fat
al error LNK1181: cannot open input file 'cperl527.lib''ccode_argv.exe' is not r
ecognized as an internal or external command,
operable program or batch file.
not ok 2 - perlcc -O -r file args # TODO unreliable CC testcase

#   Failed (TODO) test 'perlcc -O -r file args'
#   at t/c_argv.t line 45.
#          got: ''
#     expected: 'ok 2
# '
ok 3 - SKIP BC 5.22
t\c_argv.pl syntax OK
ccode_argv.exe.c(1012) : warning C4146: unary minus operator applied to unsigned
 type, result still unsignedLINK : fatal error LNK1181: cannot open input file '
cperl527.lib''ccode_argv.exe' is not recognized as an internal or external comma
nd,
operable program or batch file.

#   Failed test 'issue 30: perlcc -o ccode_argv.exe; ccode_argv.exe args'
#   at t/c_argv.t line 79.
not ok 4 - issue 30: perlcc -o ccode_argv.exe; ccode_argv.exe args
#          got: ''
#     expected: 'a b c
# '
# Looks like you failed 2 tests of 4.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/4 subtests

Test Summary Report
-------------------
../cpan/B-C/t/c_argv.t (Wstat: 512 Tests: 4 Failed: 2)
  Failed tests:  1, 4
  Non-zero exit status: 2
Files=1, Tests=4,  8 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
Result: FAIL
```
because the libperl link lib couldn't be found by B::C-something when using gmake or dmake makefiles.

commit "APItest:locale.t Fix ALT_DIGITS test" fixes a test fail for me that was already fixed in p5p perl, I added extra KHW commits from p5p perl so "APItest:locale.t Fix ALT_DIGITS test" applies correctly.

### CODE REVIEW

**Comment by rurban** [comment]
I'm fine with most fixes. Just the importlib not.

Code should just use -lcperl not -lcperl528. The actual dll should be versioned of course. The staticlib maybe also. (PV is good. major only, no minor, default cygwin got that wrong).
The revert also hardcodes the PV into 527:

-PERLIMPLIB     *= $(COREDIR)\cperl$(a)
-PERLEXPLIB     *= $(COREDIR)\cperl.exp
-PERLSTATICLIB  *= ..\cperl$(PV)s$(a)
-PERLDLL                = ..\cperl$(PV).dll
+PERLIMPLIB     *= $(COREDIR)\cperl527$(a)
+PERLEXPLIB     *= $(COREDIR)\cperl527.exp
+PERLSTATICLIB  *= ..\cperl527s$(a)
+PERLDLL                = ..\cperl527.dll

I'll rather want to fix the compiler/ExtUtils::Embed problems then. This creates the -lc?perl line.
But first extend the CI coverage to find those failing cases.

The _BitScanReverse intrinsic is nice. I don't care that much for VC6 anymore. This can really wait. Agreed.

**Comment by bulk88** [comment]
The PV macro is not always needed in the makefiles. The "527" can be a literal in the makefile because Porting/bump-perl-version script find all literal 527 and bumps them.

So do you want MSVC builds to link with "cperl527.lib" (p5p/current cperl) or "cperl.lib"?

**Comment by rurban** [comment]
I don’t care much for MSVC. This is a crazy platform anyway.
Either "cperl527.lib" (p5p/current cperl) or “cperl.lib”.
In either case ExtUtils::Embed needs to be fixed to provide the correct -l line 
for embedders and the compiler.

With mingw we should adhere to the standards as on all other platforms, 
which is a -lcperl line and -L pointing the versioned path.

Reini Urban
rurban@cpan.org

**Comment by bulk88** [comment]
I did some more research, ExtUtils::Embed does not supply the correct command lines because it doesn't know it is running in core vs installed perl. It's .t files will change @INC based on PERL_CORE for it to pass.

B::C also changes/adds the name of MSVC libperl command line at https://github.com/perl11/cperl/blob/master/cpan/B-C/script/perlcc.PL#L670 . I made another branch at  https://github.com/perl11/cperl/commit/7bb1dafd79a96e5426a5a70670ce4be60f797bb2 with a different fix, it fixes dmake MSVC and gmake MSVC but now causes nmake MSVC to fail (missing cperl.lib file from link.exe) and I think it will break old cperls running a newer B::C. I think my original fix in "partial revert "mingw: rename importlib to libcperl.a" is correct because it is safer to leave the libperl name for MSVC as it was (cperl5XX.lib) than change the ecosystem to understand "cperl.lib" on new cperl and "cperl5XX.lib" on old cperls. Any use of "-lfoo" command line syntax for "foo.lib" is broken on MSVC builds so that all has to be special cased in the first place so leaving it as the old .lib name is safest.

**Comment by rurban** [comment]
Great, I'm fine with that then.

**Comment by rurban** [comment]
Both branches do look good now. You can merge them in your preferred order.

**Comment by rurban** [comment]
The very same commit 648360c3 ran through fine the last time. It's flapping, oh my. Don't bother for now.

**Comment by rurban** [comment]
The failed IPC-Cmd test is a flapper, and can be ignored.

Oops, let me check smoke/merge_dlltool_def_file again.
You removed the best way to create the implib via -out-implib and added it via dlltool, which is also broken, I think.
I see the problem with parallel builds, but this should be fixed without dlltool. No broken tools please.

**Comment by rurban** [comment]
Oops, veto on the smoke/merge_dlltool_def_file merge.
`dlltool` is broken for 64bit. It broke many apps already, notably postgresql.
The only proper way to create the implib is via gcc --out-implib

**Comment by rurban** [comment]
Thanks, I've merged it all into smoke/merge-5279 and moved that forwards to master.
MSVC is again broken a bit.

**Pull request closed without merging**
