### PR TITLE
fix #361 "CPAN: infinite loop during checking dependencies"

### LINKED ISSUE #361: CPAN: infinite loop during checking dependencies
cperl-5.26.2 on darwin
With some modules, e.g. Protocol::HTTP2, App::cpm:

```
$ cpan Protocol::HTTP2
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/Users/user/.cpan/Metadata'
  Database was generated on Sun, 29 Apr 2018 03:54:37 GMT
Running install for module 'Protocol::HTTP2'
Checksum for /Users/user/.cpan/sources/authors/id/C/CR/CRUX/Protocol-HTTP2-1.08.tar.gz ok
---- Unsatisfied dependencies detected during ----
----      CRUX/Protocol-HTTP2-1.08.tar.gz     ----
    Module::Build::Tiny [build_requires]
Running install for module 'Module::Build::Tiny'
Checksum for /Users/user/.cpan/sources/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz ok
  LEONT/Module-Build-Tiny-0.039.tar.gz
  [configure_requires] -- NOT OK
  CRUX/Protocol-HTTP2-1.08.tar.gz
  Has already been unwrapped into directory /Users/user/.cpan/build/Protocol-HTTP2-1.08-3
---- Unsatisfied dependencies detected during ----
----      CRUX/Protocol-HTTP2-1.08.tar.gz     ----
    Module::Build::Tiny [build_requires]
Running install for module 'Module::Build::Tiny'
...
```

### PR DESCRIPTION
**Pull request by sten22**
bug occurred if only builtin modules contains in prereq

### CODE REVIEW

**Comment by rurban** [comment]
Can you regen the failing porting/customized.t test also, in the same commit? Then it's good to merge

**Comment by sten22** [comment]
done

**Comment by rurban** [comment]
I'll squash them, thanks.

**Comment by rurban** [comment]
Thanks, merged as 84090a32e95396865be442e957e903bb49a0cf6f

**Pull request closed without merging**
