### PR TITLE
Bugfix/win32

### PR DESCRIPTION
**Pull request by bulk88**
These patches make the win32 build almost pass. Not every patch in this branch is the **right way**  or only wayto fix the problem, just a way that I thought of. So some of the patches should go in, others you need to think about a little, so don't merge this, you probably want to cherry pick out of it for your own testing. Read the commit bodies, they say which patches are sketchy in design.

```
Test Summary Report
-------------------
comp/require.t                                                  (Wstat: 0 Tests:
 57 Failed: 1)
  Failed test:  52
op/signatures.t                                                 (Wstat: 0 Tests:
 1164 Failed: 0)
  TODO passed:   1041
../dist/Math-BigRat/t/biglog.t                                  (Wstat: 1280 Tes
ts: 9 Failed: 0)
  Non-zero exit status: 5
  ^^^^^^^^^^5 == SEGV, probably a write after free somewhere, I might later Dr Memory it
  Parse errors: Bad plan.  You planned 17 tests but ran 9.
Files=2395, Tests=705323, 1627 wallclock secs (64.52 usr +  4.33 sys = 68.84 CPU
)
Result: FAIL
dmake:  Error code 131, while making 'test'

C:\sources\cperl\win32>
```

../dist/Math-BigRat/t/biglog.t SEGV callstack, not very interesting since the corruption occured elsewhere

```
    ntdll.dll!_RtlpCoalesceFreeBlocks@16()  + 0xf8f 
    ntdll.dll!_RtlpExtendHeap@8()  + 0xa1   
    ntdll.dll!_RtlAllocateHeap@12()  + 0x1873   
    msvcr71.dll!_heap_alloc(unsigned int size=21)  Line 212 C
    msvcr71.dll!_nh_malloc(unsigned int size=21, int nhFlag=0)  Line 113    C
    msvcr71.dll!malloc(unsigned int size=21)  Line 54 + 0xf C
    cperl522.dll!VMem::Malloc(unsigned int size=9)  Line 151 + 0xe  C
    cperl522.dll!PerlMemMalloc(IPerlMem * piPerl=0x00363ffc, unsigned int size=9)  Line 296 + 0x14  C
    cperl522.dll!Perl_safesysmalloc(unsigned int size=9)  Line 152  C
    cperl522.dll!Perl_sv_grow(interpreter * my_perl=0x00366004, sv * const sv=0x00e55444, unsigned int newlen=8)  Line 1633 + 0x6   C
    cperl522.dll!Perl_sv_setpvn(interpreter * my_perl=0x00366004, sv * const sv=0x00e55444, const char * const ptr=0x00e5a200, const unsigned int len=7)  Line 4932 + 0x22  C
    cperl522.dll!Perl_newSVpvn(interpreter * my_perl=0x00366004, const char * const buffer=0x00e5a200, const unsigned int len=7)  Line 9205 + 0x1d  C
    cperl522.dll!S_unpack_rec(interpreter * my_perl=0x0012f89c, tempsym * symptr=0x00000000, const char * s=0x00360178, const char * strbeg=0x00000001, const char * strend=0x00bf0000, const char * * new_s=0x0012f8be)  Line 1089 + 0x10  C
    cperl522.dll!Perl_unpackstring(interpreter * my_perl=0x00366004, const char * pat=0x00e5a764, const char * patend=0x00e5a8ca, const char * s=0x00e5a0ec, const char * strend=0x00e5a5cd, unsigned long flags=0)  Line 835 + 0x30    C
    cperl522.dll!Perl_pp_unpack(interpreter * my_perl=0x00e5a5cd)  Line 1831    C
    cperl522.dll!Perl_runops_standard(interpreter * my_perl=0x00366004)  Line 41 + 0x4  C
    cperl522.dll!S_run_body(interpreter * my_perl=0x00e5b000, long oldscope=1)  Line 2473 + 0xa C
    cperl522.dll!perl_run(interpreter * my_perl=0x00366004)  Line 2396 + 0x8    C
    cperl522.dll!RunPerl(int argc=4, char * * argv=0x01362cc8, char * * env=0x00363140)  Line 263 + 0x6 C
    perl.exe!mainCRTStartup()  Line 398 + 0xe   C
    kernel32.dll!_BaseProcessStart@4()  + 0x23
```

```
C:\sources\cperl\win32>plrun1 comp/require.t

C:\sources\cperl\win32>cd ..\t   & perl harness -v comp/require.t   & cd ..\win3
2
comp/require.t ..
1..57
ok 1 - require 5.005 try 1
ok 2 - require 5.005 try 2
ok 3 - require 5.005 try 3
ok 4 - require 5.005 try 4
ok 5 - require 5.5.630
ok 6 - require(v5.5.630) with parens [perl #124153]
ok 7 - require v5 ignores sub named v5
ok 8 - require 10.0.2
ok 9 - require 5.005_63
ok 10 - require 10.2
ok 11 - require 10.000_02
ok 12 - 5.5.1 gt v5.5
ok 13 - v5.5.640 eq \x{5}\x{5}\x{280}
ok 14 - v7.15 eq \x{7}\x{f}
ok 15 - v1.20.300.4000.50000.600000 eq ...
ok 16 - require 5.11.0
ok 17 - BEGIN { require 5.11.0}
ok 18 - require bleah.pm
ok 19 - require returning 0
ok 20 - %INC not updated
ok 21 - exp 1; bleah.flg
ok 22 - exp 1; require bleah.pm with flag file
ok 23 - exp 1; -e flag_file
ok 24 - exp 1; exists $INC{'bleah.pm}
ok 25 - exp 0; bleah.flg
ok 26 - exp 0; require bleah.pm with flag file
ok 27 - exp 0; -e flag_file
ok 28 - exp 0; exists $INC{'bleah.pm}
ok 29 - syntax error
ok 30 - cached %INC
ok 31 - eval { require 'bleah.pm' }
ok 32 - Compilation failed
ok 33 - -e flag_file
ok 34 - $INC{'bleah.pm'}
ok 35 - do_require '1';
ok 36 - bleah.do
ok 37 - require() context
ok 38 - require() context
ok 39 - require() context
ok 40 - require() context
ok 41 - require() context
ok 42 - require() context
ok 43 - require() context
ok 44 - require() context
ok 45 - RT #24404
ok 46 - [perl #24482] require CORE::foo
ok 47 - expected error
# .pmc files should be loaded, so test that
# Sleeping for 2 seconds before creating some more files
ok 48 - urkkk.pm branch B
ok 49 - krunch.pm branch B
ok 50 - pmc_dies
ok 51 - require op
not ok 52 - require(func())
ok 53 - require ignores I/O layers
not ok 54 # TODO CM-833 require does not localise %^H at run time
ok 55 # UTF-16BE
ok 56 # UTF-16LE
ok 57 # UTF-8
Failed 1/57 subtests

Test Summary Report
-------------------
comp/require.t (Wstat: 0 Tests: 57 Failed: 1)
  Failed test:  52
Files=1, Tests=57,  2 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
Result: FAIL

C:\sources\cperl\win32>
```

modifying the error message to dump $@

```
not ok 52 - require(func()) >>>>Can't locate DynaLoader.pm in @INC (you may need
 to install the DynaLoader module) (@INC contains: . ../lib ../ext/re) at ../lib
/Win32.pm line 8.
Compilation failed in require at ../lib/Cwd.pm line 624.
BEGIN failed--compilation aborted.
<<<<
```

something wiped %INC at some point earlier in comp/require.t and the DynaLoader.pm entry was removed. I have a fix for require.t but kindda hackish so I didn't push it.

### CODE REVIEW

**Comment by rurban** [comment]
Great, we are getting there.

**Comment by rurban** [comment]
rebased to `bugfix/gh39-win32` d65a594d6da4bf60356200c9e80d93cbd1db82ff
windows ci: https://ci.appveyor.com/project/rurban/cperl/build/job/6i0y3s0urvyksmc2
linux+osx: https://travis-ci.org/perl11/cperl/builds/80532598

**Comment by rurban** [comment]
Nice, only 

```
op/signatures.t                                                 (Wstat: 0 Tests: 1164 Failed: 0)
  TODO passed:   1041
porting/FindExt.t                                               (Wstat: 0 Tests: 2 Failed: 2)
  Failed tests:  1-2
Files=2388, Tests=720156, 285 wallclock secs (69.25 usr  6.73 sys + 342.48 cusr 32.02 csys = 450.48 CPU)
Result: FAIL
```

https://travis-ci.org/perl11/cperl/jobs/80532599#L3644

This should be trivial to fix. Getting appveyor to install mingw will be harder: https://ci.appveyor.com/project/rurban/cperl/build/5.22.2.2/job/6i0y3s0urvyksmc2

**Comment by bulk88** [comment]
I think commit "ExtUtils-Embed 1.34c: optimize boot_DynaLoader" and "boot_DynaLoader now on all platforms" are causing this by not doing pushmarks the way I wrote it earlier.

crashed process name .\perl .\echo10292 1
parent process name .\perl -I.. -MTestInit -T op/taint.t

contents of .\echo10292

```
print "@ARGV\n"
```

```
Unhandled exception at 0x28091eb9 (cperl522.dll) in perl.exe: 0xC0000005: Access violation writing location 0xb1f45d00.
```

```
    cperl522.dll!Perl_xs_boot_epilog(interpreter * my_perl=0x0036465c, const long ax=1819242325)  Line 5110 + 0x10  C
    cperl522.dll!boot_DynaLoader(interpreter * my_perl=0x0036465c, cv * cv=0x008fa3fc)  Line 515 + 0x7  C
    cperl522.dll!xs_init(interpreter * my_perl=0x0036465c)  Line 12 C
    cperl522.dll!S_parse_body(interpreter * my_perl=0x00364720, char * * env=0x00363030, void (interpreter *)* xsinit=0x280c5585)  Line 2227 + 0x4  C
    cperl522.dll!perl_parse(interpreter * my_perl=0x0036465c, void (interpreter *)* xsinit=0x280c5585, int argc=3, char * * argv=0x00363ee0, char * * env=0x00363030)  Line 1627    C
    cperl522.dll!RunPerl(int argc=3, char * * argv=0x01363ee0, char * * env=0x00363030)  Line 254 + 0x10    C
    perl.exe!mainCRTStartup()  Line 398 + 0xe   C
    kernel32.dll!_BaseProcessStart@4()  + 0x23  
```

```
void
Perl_xs_boot_epilog(pTHX_ const I32 ax)
{
  if (PL_unitcheckav)
    call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;<<<<<<<<<<<crash line
}
```

```
    XSRETURN_YES;
28091EA9 8B 44 24 0C      mov         eax,dword ptr [esp+0Ch] ; probably var ax
28091EAD 8B 56 0C         mov         edx,dword ptr [esi+0Ch] ;my_perl->Istack_base
28091EB0 8D 8E C4 00 00 00 lea         ecx,[esi+0C4h] 
28091EB6 C1 E0 02         shl         eax,2 
28091EB9 89 0C 10         mov         dword ptr [eax+edx],ecx <<<<<<<<<<<<fault INS, write to perl stack
28091EBC 8B 4E 0C         mov         ecx,dword ptr [esi+0Ch] 
28091EBF 03 C8            add         ecx,eax 
28091EC1 89 0E            mov         dword ptr [esi],ecx 
28091EC3 5E               pop         esi  
}
28091EC4 C3               ret
```

register edx is 0x00363EF7, an allocated memory block

register eax is 0xB1BDBD54 (this is var ax probably), high bit on (upper 2 GB) pointers dont exist on 32 bit windows, so this is very wrong and no memory exists at this address

final test summary of https://github.com/bulk88/cperl/tree/bugfix/gh39-b88WIPcommits

```
Test Summary Report
-------------------
comp/require.t                                                  (Wstat: 0 Tests:
 57 Failed: 1)
  Failed test:  52
op/signatures.t                                                 (Wstat: 0 Tests:
 1164 Failed: 0)
  TODO passed:   1041
op/taint.t                                                      (Wstat: 0 Tests:
 801 Failed: 2)
  Failed tests:  1, 393
^^^^^^^^^^^child procs SEGV
porting/podcheck.t                                              (Wstat: 0 Tests:
 1354 Failed: 2)
  Failed tests:  178, 941
../dist/Math-BigRat/t/biglog.t                                  (Wstat: 1280 Tes
ts: 9 Failed: 0)
  Non-zero exit status: 5
^^^^^^^^^^^^^^5==SEGV
  Parse errors: Bad plan.  You planned 17 tests but ran 9.
Files=2395, Tests=708361, 4397 wallclock secs (63.22 usr +  3.17 sys = 66.39 CPU
)
Result: FAIL
dmake:  Error code 133, while making 'test'
```

**Comment by rurban** [comment]
Ok, so we need the PUSHMARK.

**Comment by rurban** [comment]
New attempt with `bugfix/gh39-win32-pushmark`, without the parallel build and Config improvements

**Comment by rurban** [comment]
Pushed to master, should work hopefully. 
dist/Math-BigRat/t/biglog.t would need a seperate ticket if not. 
The upstream maintainer mentioned at p5p about a new known bug with log2.

**Pull request closed without merging**
